export default  () => {
    return [
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
        {
          keyword: 'user experience design',
          Role: 'What is user experience design?',
          kd: 14,
          sv: 2000,
          gsv: 1233,
          cpc: '4,59',
          et: 66,
          updated: 'Today',
          tkeyword: 'ux'
        },
        {
          keyword: 'ux design',
          Role: 'How ux design can be used to generate more revenue?',
          kd: 84,
          sv: 3123,
          gsv: 543,
          cpc: '4,55',
          et: 23,
          updated: 'Yesterday',
          tkeyword: 'user experience'
        },
        {
          keyword: 'ux ui designer',
          Role: 'What is the role of UI UX designer?',
          kd: 100,
          sv: 1232,
          gsv: 2543,
          cpc: '3,22',
          et: 54,
          updated: 'Yesterday',
          tkeyword: 'ui'
        },
        {
          keyword: 'ui ux',
          Role: 'How does UI and UX are different?',
          kd: 69,
          sv: 766,
          gsv: 3211,
          cpc: '1,52',
          et: 23,
          updated: '1 JAN 2024',
          tkeyword: 'ux design'
        },
        {
          keyword: 'google ux design',
          Role: 'How does Google uses UX design?',
          kd: 29,
          sv: 3544,
          gsv: 2321,
          cpc: '1,57',
          et: 65,
          updated: '15 JAN 2024',
          tkeyword: 'ux/ui'
        },
    ];
}